export const killerPerks = [
  "Agitation",
  "Barbecue & Chilli",
  "Bamboozle",
  "Beast of Prey",
  "Bitter Murmur",
  "Deerstalker",
  "Enduring",
  "Fire Up",
  "Franklin's Demise",
  "Gearhead",
  "Grim Embrace",
  "Hoarder",
  "Hubris",
  "Hysteria",
  "I'm All Ears",
  "Infectious Fright",
  "Iron Maiden",
  "Knock Out",
  "Languid Touch",
  "Lethal Pursuer",
  "Leverage",
  "Lightborn",
  "Machine Learning",
  "Mad Grit",
  "Make Your Choice",
  "Merciless Storm",
  "Mindbreaker",
  "Monitor & Abuse",
  "Nemesis",
  "No Holds Barred",
  "No Quarter",
  "No Way Out",
  "Nowhere to Hide",
  "Oppression",
  "Overcharge",
  "Overwhelming Presence",
  "Play with Your Food",
  "Pop Goes the Weasel",
  "Predator",
  "Rancor",
  "Rapid Brutality",
  "Remember Me",
  "Save the Best for Last",
  "Scourge Hook: Floods of Rage",
  "Scourge Hook: Gift of Pain",
  "Scourge Hook: Hangman's Trick",
  "Scourge Hook: Jagged Compass",
  "Scourge Hook: Pain Resonance",
  "Septic Touch",
  "Shadowborn",
  "Spirit Fury",
  "Starstruck",
  "Stridor",
  "Superior Anatomy",
  "Surge",
  "Territorial Imperative",
  "The Third Seal",
  "Thrill of the Hunt",
  "Two Can Play",
  "Undying",
  "Wretched Fate",
  "Hex: Overture of Doom",
  "Ravenous",
  "Wandering Eye",
  "Help Wanted",
  "Haywire",
  "Phantom Fear",
  "None Are Free",
  "Forever Entwined",
  "Hex: Nothing But Misery"
];

export const survivorPerks = [
  "Adrenaline",
  "Aftercare",
  "Better Together",
  "Bond",
  "Boon: Circle of Healing",
  "Boon: Dark Theory",
  "Borrowed Time",
  "Breakdown",
  "Calm Spirit",
  "Clarity",
  "Counterforce",
  "Dance With Me",
  "Dead Hard",
  "Decisive Strike",
  "Empathy",
  "Fast Track",
  "Flashbang",
  "Flip-Flop",
  "For The People",
  "Guardian",
  "Hope",
  "Iron Will",
  "Kindred",
  "Leader",
  "Lightweight",
  "Lucky Star",
  "Made For This",
  "No Mither",
  "Off The Record",
  "Open-Handed",
  "Overzealous",
  "Prove Thyself",
  "Quick & Quiet",
  "Quick Gambit",
  "Reactive Healing",
  "Resilience",
  "Self-Care",
  "Slippery Meat",
  "Small Game",
  "Solidarity",
  "Sprint Burst",
  "Stake Out",
  "Streetwise",
  "Technician",
  "Tenacity",
  "Unbreakable",
  "Up The Ante",
  "Vigil",
  "Windows of Opportunity",
  "We're Gonna Live Forever",
  "Teamwork: Toughen Up",
  "Apocalyptic Ingenuity",
  "Conviction",
  "Last Stand",
  "Come and Get Me!",
  "Ghost Notes",
  "One-Two-Three-Four!",
  "Road Life"
];

export const maps = [
  "Nostromo Wreckage",
  "Toba Landing",
  "Decimated Borgo",
  "Fallen Refuge",
  "Withered Isle",
  "Foresaken Boneyard",
  "RPD",
  "Silent Hill",
  "Grave of Grenvale",
  "Hawkins Lab",
  "Ormond",
  "Yamaoka Estate",
  "Gideon Meat Plant",
  "Badham Preschool",
  "Backwater Swamp",
  "Red Forest",
  "Lery's",
  "Haddonfield",
  "Crotus Prenn Asylum",
  "Autohaven Wreckers",
  "Coldwind Farm",
  "The Macmillan Estate"
];

export const killers = [
  "The Trapper",
  "The Wraith",
  "The Hillbilly",
  "The Nurse",
  "The Shape",
  "The Hag",
  "The Doctor",
  "The Huntress",
  "The Cannibal",
  "The Nightmare",
  "The Pig",
  "The Clown",
  "The Spirit",
  "The Legion",
  "The Plague",
  "The Ghost Face",
  "The Demogorgon",
  "The Oni",
  "The Deathslinger",
  "The Executioner",
  "The Blight",
  "The Twins",
  "The Trickster",
  "The Nemesis",
  "The Cenobite",
  "The Artist",
  "The Onryō",
  "The Dredge",
  "The Mastermind",
  "The Knight",
  "The Skull Merchant",
  "The Singularity",
  "The Xenomorph",
  "The Good Guy",
  "The Unknown",
  "The Lich"
];
